import Head from 'next/head'
import { useState } from 'react'
import Image from 'next/image'
import { FaChessQueen } from 'react-icons/fa'

import { executeHillClimbing } from '../utils'

const initialState = [
  [true, false, false, false, false, false, false, false],
  [true, false, false, false, false, false, false, false],
  [false, false, false, true, false, false, false, false],
  [false, false, false, false, true, false, false, false],
  [false, false, false, false, true, false, false, false],
  [false, false, false, false, false, false, true, false],
  [false, false, true, false, false, false, false, false],
  [false, false, false, false, false, false, false, true],
]

const styleBoard = {
  width: '100vw',
  height: '100vh',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  flexDirection: 'column',
}

const styleBlock = {
  width: '80px',
  height: '80px',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  border: '1px solid #000',
}

export default function Home() {
  const [board, setBoard] = useState(initialState)
  const [message, setMessage] = useState('')

  function reset() {
    setBoard(initialState)
    setMessage('')
  }

  function resolver() {
    const finalBoard = executeHillClimbing(board)
    if (finalBoard === -1) {
      setMessage('count not solve')
      return
    }
    setBoard(finalBoard)
  }

  return (
    <div>
      <Head>
        <title>N queens - Hill climbing</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={styleBoard}>
        {board.map((arr, idx) => {
          return (
            <div key={idx} style={{ display: 'flex' }}>
              {arr.map((value, idy) => {
                const isOdd = (idx + idy) % 2 === 1

                if (value) {
                  return (
                    <div key={idy} style={{ ...styleBlock, backgroundColor: isOdd ? 'lightgray' : '#fff' }}>
                      <FaChessQueen size={20} />
                    </div>
                  )
                }
                return <div key={idy} style={{ ...styleBlock, backgroundColor: isOdd ? 'lightgray' : '#fff' }}></div>
              })}
            </div>
          )
        })}

        <span>{message}</span>

        <button
          onClick={resolver}
          style={{
            height: '2rem',
            width: '250px',
            margin: '20px 0',
            outline: 'none',
            border: 'none',
            borderRadius: '8px',
            cursor: 'pointer',
            fontWeight: 'bold',
            fontSize: '15px',
          }}
        >
          Resolver
        </button>
        <button
          onClick={reset}
          style={{
            height: '2rem',
            width: '250px',
            outline: 'none',
            border: 'none',
            borderRadius: '8px',
            cursor: 'pointer',
            fontWeight: 'bold',
            fontSize: '15px',
          }}
        >
          Reset
        </button>
      </main>
    </div>
  )
}
